baseURL = 'https://marrani.lol/'
title = 'marrani.lol'
copyright = 'marrani.lol'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
  weight = 1
  languageCode = 'en-US'
  languageName = 'English'
  languageNameShort = 'en'
  [languages.it]
  weight = 2
  languageCode = 'it-IT'
  languageName = 'Italiano'
  languageNameShort = 'it'


[params]
  favicon = "favicon.ico"
  date_format = "2006-01-02"
  description = "Resistence is futile! All your pixels belong to us!"
