baseURL = 'https://marrani.lol/'
title = 'marrani.lol'
copyright = 'marrani.lol'

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  anchorLineNos = false
  codeFences = false
  guessSyntax = false
  hl_Lines = ''
  hl_inline = false
  lineAnchors = ''
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = false
  style = 'bw'
  tabWidth = 4
  wrapperClass = 'highlight'

[taxonomies]
author = 'authors'
tag = 'tags'

[outputs]
  home = ["html", "rss"]
  posts = ["html", "rss"]

[params]
  favicon = "favicon.ico"
  date_format = "2006/01"
  group_by_date = false
  show_description = true
  toc = true

[sitemap]
  changeFreq = ''
  disable = false
  filename = "sitemap.xml"
  priority = -1

[minify]
  minifyOutput = true
