baseURL = 'https://marrani.lol/'
languageCode = 'it-IT'
title = 'marrani.lol'

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'rrt'
    tabWidth = 4

[params]
  favicon = "favicon.ico"
  [params.theme_config]
    show_description = true
    back_home_text = ".."
    date_format = "2006-01-02"
